export enum ProductType {
  ASR = 'ASR',
  CONVERSATIONS = 'CONVERSATIONS',
  IN_APP_VOICE = 'IN-APP-VOICE',
  MESSAGES = 'MESSAGES',
  NUMBER_INSIGHT = 'NUMBER-INSIGHT',
  SMS = 'SMS',
  VERIFY_API = 'VERIFY-API',
  VOICE_CALL = 'VOICE-CALL',
  WEBSOCKET_CALL = 'WEBSOCKET-CALL',
}
